CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('ACTIVE', 'WITHDRAWN')),
    created_at TIMESTAMPTZ NOT NULL,
    deleted_at TIMESTAMPTZ
);

CREATE TABLE sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    refresh_token_hash VARCHAR(255) NOT NULL,
    user_agent VARCHAR(255),
    ip INET,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ
);

CREATE TABLE tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(30) NOT NULL UNIQUE,
    name VARCHAR(50) NOT NULL,
    order_no INT NOT NULL
);

CREATE TABLE documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL REFERENCES users(id),
    title VARCHAR(255) NOT NULL,
    file_key VARCHAR(512) NOT NULL,
    file_hash VARCHAR(64) NOT NULL,
    mime_type VARCHAR(100) NOT NULL,
    size_bytes BIGINT NOT NULL,
    page_count INT,
    parse_status VARCHAR(20) NOT NULL CHECK (parse_status IN ('PENDING', 'PARSING', 'EXTRACTING', 'DONE', 'FAILED')),
    uploaded_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    deleted_at TIMESTAMPTZ
);

CREATE TABLE document_tags (
    document_id BIGINT NOT NULL REFERENCES documents(id),
    tag_id BIGINT NOT NULL REFERENCES tags(id),
    created_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (document_id, tag_id)
);

CREATE TABLE pages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL REFERENCES documents(id),
    page_no INT NOT NULL,
    width NUMERIC,
    height NUMERIC,
    text_layer TEXT,
    UNIQUE (document_id, page_no)
);

CREATE TABLE sections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL REFERENCES documents(id),
    parent_id BIGINT REFERENCES sections(id),
    source VARCHAR(20) NOT NULL CHECK (source IN ('ORIGINAL', 'EXTRACTED')),
    title VARCHAR(255) NOT NULL,
    level INT NOT NULL,
    page_from INT,
    page_to INT,
    order_no INT NOT NULL
);

CREATE TABLE extracted_elements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL REFERENCES documents(id),
    section_id BIGINT REFERENCES sections(id),
    page_no INT NOT NULL,
    kind VARCHAR(30) NOT NULL CHECK (kind IN ('NUMBER', 'TABLE_CELL', 'CLAIM', 'DATE')),
    raw_text TEXT,
    normalized_value NUMERIC,
    unit VARCHAR(20),
    bbox JSONB
);

CREATE TABLE validation_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_code VARCHAR(50) NOT NULL,
    version INT NOT NULL,
    target_kind VARCHAR(30),
    expression TEXT NOT NULL,
    tolerance NUMERIC,
    severity VARCHAR(20) NOT NULL CHECK (severity IN ('ERROR', 'WARNING', 'INFO')),
    message_template TEXT,
    effective_from DATE,
    effective_to DATE,
    UNIQUE (rule_code, version)
);

CREATE TABLE review_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL REFERENCES documents(id),
    status VARCHAR(20) NOT NULL CHECK (status IN ('PENDING', 'RUNNING', 'DONE', 'FAILED')),
    review_status VARCHAR(20) NOT NULL CHECK (review_status IN ('IN_REVIEW', 'COMPLETED')),
    review_score INT,
    ruleset_version INT,
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    error_code VARCHAR(50)
);

CREATE TABLE findings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL REFERENCES review_jobs(id),
    rule_id BIGINT REFERENCES validation_rules(id),
    severity VARCHAR(20) NOT NULL CHECK (severity IN ('ERROR', 'WARNING', 'INFO')),
    category VARCHAR(50) NOT NULL,
    confidence NUMERIC CHECK (confidence BETWEEN 0 AND 1),
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    calc_expr TEXT,
    expected_value NUMERIC,
    actual_value NUMERIC,
    page_no INT,
    status VARCHAR(20) NOT NULL CHECK (status IN ('OPEN', 'ACCEPTED', 'REJECTED'))
);

CREATE TABLE finding_evidence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    finding_id BIGINT NOT NULL REFERENCES findings(id),
    page_no INT NOT NULL,
    bbox JSONB,
    quote TEXT,
    chunk_id VARCHAR(100),
    score NUMERIC
);

CREATE TABLE finding_elements (
    finding_id BIGINT NOT NULL REFERENCES findings(id),
    element_id BIGINT NOT NULL REFERENCES extracted_elements(id),
    role VARCHAR(30) CHECK (role IN ('SUBJECT', 'REFERENCE', 'EXPECTED', 'ACTUAL', 'COMPARE')),
    PRIMARY KEY (finding_id, element_id)
);

CREATE TABLE finding_decisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    finding_id BIGINT NOT NULL REFERENCES findings(id),
    user_id BIGINT NOT NULL REFERENCES users(id),
    decision VARCHAR(20) NOT NULL CHECK (decision IN ('ACCEPT', 'REJECT')),
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE annotations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL REFERENCES review_jobs(id),
    finding_id BIGINT REFERENCES findings(id),
    author_id BIGINT NOT NULL REFERENCES users(id),
    body TEXT NOT NULL,
    page_no INT,
    bbox JSONB,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    deleted_at TIMESTAMPTZ
);

CREATE INDEX idx_sessions_user_revoked ON sessions (user_id, revoked_at);
CREATE INDEX idx_documents_owner_deleted_updated ON documents (owner_id, deleted_at, updated_at DESC);
CREATE UNIQUE INDEX uq_documents_owner_file_hash_active ON documents (owner_id, file_hash) WHERE deleted_at IS NULL;
CREATE INDEX idx_document_tags_tag_document ON document_tags (tag_id, document_id);
CREATE INDEX idx_sections_document_source_order ON sections (document_id, source, order_no);
CREATE INDEX idx_extracted_elements_document_page ON extracted_elements (document_id, page_no);
CREATE INDEX idx_review_jobs_document_latest ON review_jobs (document_id, id DESC);
CREATE UNIQUE INDEX uq_review_jobs_document_running ON review_jobs (document_id) WHERE status = 'RUNNING';
CREATE INDEX idx_findings_job_severity_confidence ON findings (job_id, severity, confidence DESC);
CREATE INDEX idx_finding_evidence_finding_page ON finding_evidence (finding_id, page_no);
CREATE INDEX idx_finding_elements_element ON finding_elements (element_id);
CREATE INDEX idx_finding_decisions_finding_created ON finding_decisions (finding_id, created_at DESC);
CREATE INDEX idx_annotations_job_deleted_page ON annotations (job_id, deleted_at, page_no);
CREATE INDEX idx_annotations_finding_deleted ON annotations (finding_id, deleted_at);

INSERT INTO tags (code, name, order_no) VALUES
    ('AI', 'AI', 1),
    ('GOV_PROJECT', '정부과제', 2),
    ('RND', 'R&D', 3),
    ('INVESTMENT', '투자', 4),
    ('ROBOTICS', '로보틱스', 5),
    ('HEALTHCARE', '헬스케어', 6),
    ('GREEN', '친환경', 7);
