-- 검토(ReviewJob/Finding) 파이프라인을 프런트 계약에 맞춘다.
--
-- baseline 의 review_jobs / findings / finding_evidence 는 severity(ERROR|WARNING|INFO) ·
-- status(OPEN|ACCEPTED|REJECTED) 체계로 잡혀 있어 화면이 쓰는
-- FindingType(ERROR|NEEDS_CHECK|NO_EVIDENCE) · Verdict(PENDING|ACCEPTED|REJECTED) 와 맞지 않는다.
-- 아직 이 테이블들에 쓰는 코드가 없어 데이터가 없으므로, NOT NULL 컬럼을 억지로 채우는 대신
-- 통째로 다시 만든다. 참조 테이블(annotations 등)은 ERD 유지를 위해 같은 모양으로 재생성한다.

ALTER TABLE documents ADD COLUMN version INT NOT NULL DEFAULT 1;
ALTER TABLE documents ADD COLUMN summary TEXT;

-- 원문 뷰어가 렌더링하는 블록 배열. [{id,kind,text,caption,head,rows}]
ALTER TABLE pages ADD COLUMN blocks JSONB;
ALTER TABLE pages ADD COLUMN section_id BIGINT REFERENCES sections(id);

DROP TABLE IF EXISTS annotations;
DROP TABLE IF EXISTS finding_decisions;
DROP TABLE IF EXISTS finding_elements;
DROP TABLE IF EXISTS finding_evidence;
DROP TABLE IF EXISTS findings;
DROP TABLE IF EXISTS review_jobs;

CREATE TABLE review_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL REFERENCES documents(id),
    status VARCHAR(20) NOT NULL CHECK (status IN ('PENDING', 'RUNNING', 'PARTIAL', 'DONE', 'FAILED')),
    review_status VARCHAR(20) NOT NULL CHECK (review_status IN ('IN_REVIEW', 'COMPLETED')),
    phase VARCHAR(10) NOT NULL CHECK (phase IN ('PARSE', 'ANALYZE')),
    -- 진행률은 폴링마다 쓰지 않고 started_at + 소요시간으로 읽는 시점에 계산한다.
    parse_duration_ms INT NOT NULL,
    analyze_duration_ms INT NOT NULL,
    analyze_started_at TIMESTAMPTZ,
    steps JSONB,
    partial_failures JSONB,
    started_at TIMESTAMPTZ NOT NULL,
    finished_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    error_code VARCHAR(50)
);

CREATE TABLE findings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL REFERENCES review_jobs(id) ON DELETE CASCADE,
    finding_type VARCHAR(20) NOT NULL CHECK (finding_type IN ('ERROR', 'NEEDS_CHECK', 'NO_EVIDENCE')),
    method VARCHAR(20) NOT NULL CHECK (method IN ('DETERMINISTIC', 'RAG', 'MANUAL')),
    verdict VARCHAR(20) NOT NULL CHECK (verdict IN ('PENDING', 'ACCEPTED', 'REJECTED')),
    section_id BIGINT REFERENCES sections(id),
    page_no INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    confidence NUMERIC NOT NULL CHECK (confidence BETWEEN 0 AND 1),
    calculation JSONB,
    order_no INT NOT NULL,
    decided_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE finding_evidence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    finding_id BIGINT NOT NULL REFERENCES findings(id) ON DELETE CASCADE,
    -- 원문 블록 id (b-{page}-{index}). 화면의 양방향 앵커가 이 값으로 하이라이트를 찾는다.
    anchor_id VARCHAR(100) NOT NULL,
    page_no INT NOT NULL,
    label TEXT,
    selected_text TEXT,
    order_no INT NOT NULL
);

CREATE TABLE finding_decisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    finding_id BIGINT NOT NULL REFERENCES findings(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id),
    verdict VARCHAR(20) NOT NULL CHECK (verdict IN ('PENDING', 'ACCEPTED', 'REJECTED')),
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE annotations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL REFERENCES review_jobs(id) ON DELETE CASCADE,
    finding_id BIGINT REFERENCES findings(id) ON DELETE CASCADE,
    author_id BIGINT NOT NULL REFERENCES users(id),
    body TEXT NOT NULL,
    anchor_id VARCHAR(100),
    page_no INT,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    deleted_at TIMESTAMPTZ
);

CREATE INDEX idx_review_jobs_document_latest ON review_jobs (document_id, id DESC);
CREATE UNIQUE INDEX uq_review_jobs_document_active ON review_jobs (document_id)
    WHERE status IN ('PENDING', 'RUNNING');
CREATE INDEX idx_findings_job_order ON findings (job_id, order_no);
CREATE INDEX idx_findings_job_verdict ON findings (job_id, verdict);
CREATE INDEX idx_finding_evidence_finding_order ON finding_evidence (finding_id, order_no);
CREATE INDEX idx_finding_decisions_finding_created ON finding_decisions (finding_id, created_at DESC);
CREATE INDEX idx_annotations_job_deleted ON annotations (job_id, deleted_at);
